# **video 8-- tensor creation**

In [0]:
!pip3 install torch torchvision

In [0]:
import torch

In [0]:
print(torch.__version__)

1.1.0


In [0]:
torch.cuda.is_available()

True

In [0]:
torch.version.cuda

'10.0.130'

In [0]:
t=torch.Tensor()

In [0]:
print(t.device)

cpu


In [0]:
print(t.dtype)

torch.float32


In [0]:
print(t.layout) #

torch.strided


In [0]:
device=torch.device('cuda:0')
device

device(type='cuda', index=0)

**Tensor operations should be done on tensors of same dtype and same device(CPU - GPU operations not allowed)**



**CREATING TENSORS---- 4 WAYS TO DO SO**

In [0]:
import numpy as np
data= np.array([1,2,3])
type(data)

numpy.ndarray

In [0]:
d0=torch.Tensor(data)  #this is class constructor of torch.Tensor class
print(d0.dtype)

torch.float32


In [0]:
d1=torch.tensor(data)
print(d.dtype)# this is the function of the class, notice the change in the o/p data type

NameError: ignored

In [0]:
d2=torch.as_tensor(data)

In [0]:
d3=torch.from_numpy(data)
print(d3)

**Tensor creation options when no data is available**

In [0]:
torch.eye(3)  #identity matrix

In [0]:
torch.zeros(2,2) #rank 2, 2 axes

In [0]:
torch.zeros(2)

In [0]:
torch.ones(3,3)

In [0]:
torch.rand(5)

In [0]:
torch.rand(3,4)

# **VIDEO 9-- BEST OPTIONS TO CREATE TENSORS**

**Blog post of video9** http://deeplizard.com/learn/video/AglLTlms7HU

In [0]:
import torch
import numpy as np

In [0]:
data= np.array([1,2,4])
t1=torch.Tensor(data) #class constructor
t2=torch.tensor(data) #all 3 are factory functions, factory functions has better documentation, methods and interfaces
t3=torch.as_tensor(data)
t4=torch.from_numpy(data)

In [0]:
print(t1, t2,t3,t4)

In [0]:
print(t1.dtype,t2.dtype, t3.dtype, t4.dtype) #constructor uses global default dtype value and factory functions retain the dtype of ip

**Setting dtype of tensor**

>               
Constructor cant set the dtype of tensor


In [0]:
torch.tensor(np.array([1,2,5]), dtype=torch.float64 )

In [0]:
torch.tensor(np.array([1,2,-5]), dtype=torch.uint8 )

**Memory sharing Vs Memory Copying**

In [28]:
data=np.array([1,5,7,8])
data

array([1, 5, 7, 8])

In [0]:
t1= torch.Tensor(data)
t2=torch.tensor(data)
t3=torch.as_tensor(data)
t4=torch.from_numpy(data)

**now changing the data array we defined before and see how the tensors act**

In [30]:
data[0]=0
data[1]=0
data[2]=0
data[3]=0
data

array([0, 0, 0, 0])

In [31]:
print(t1)
print(t2)

tensor([1., 5., 7., 8.])
tensor([1, 5, 7, 8])


In [32]:
print(t3)
print(t4)

tensor([0, 0, 0, 0])
tensor([0, 0, 0, 0])


**key takeaway**
torch.tensor() and torch.Tensor() create an additonal copy of data in memory i.e. use new mem to create tensor from ip data

whereas torch.as_tensor() and torch.from_numpy() share the mem with numpy array

So while shifting data too and from in between numpy and torch tensors use torch.as_tensor and torch.from_numpy

# **VIDEO 10 Tensor operations**

**blog post** http://deeplizard.com/learn/video/fCVuiW9AFzY

In [0]:
import torch

In [0]:
t1=torch.tensor([[1,1,1,1],
              [2,2,2,2],
              [3,3,3,3]], dtype=torch.float32)

above tensor has shape 3*4
rank=2 (we need only 2 indices for it be accessed)
axis= 2 (1st axes has length 3, 3 arrays and 2nd axis has length 4 it has all numbers)

In [38]:
t1.size()
 #checking shape

torch.Size([3, 4])

In [40]:
t1.shape  #checking shape

torch.Size([3, 4])

In [42]:
len(t1.shape) #length of shape is nothing but rank coz it gives number of indices necessary to access the tensor

2

In [43]:
torch.tensor(t1.shape).prod() #multiplying the elements in torch.size to get total no. of elements in the tensor 

tensor(12)

In [44]:
t1.numel() #above can be done by default function numel

12

Reshaping the tensor wo changing it's shape and rank

In [46]:
t1.reshape(4,3)

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])

In [47]:
t1.reshape(12,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

In [48]:
t1.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [49]:
t1.reshape(6,2)

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])

**Squeezing opeartion removes axis of length 1 from tensor and unsqueezing operation adds the axis of length 1 to the tensor**

In [52]:
print(t1.reshape(1,12))
print(t1.reshape(1,12).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


notice the size change before and after squeeze operation

In [56]:
print(t1.reshape(1,12).squeeze())
print(t1.reshape(1,12).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


notice the size change before and after squeeze operation
dim 0 will make new dimension 1,12  i.e. new column will be added in 1st dimension and dim 1will make size 12,1 i.e new column will be added in 2nd dimension

In [62]:
print(t1.reshape(1,12).squeeze().unsqueeze(dim=0))
print(t1.reshape(1,12).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


with squeezing opearation rank of the tensor can be altered.

**Making up flatening function with the help of reshape and squeeze**

In [0]:
def flatten(t1):
  t=t1.reshape(1,-1) # -1 tells the reshape function to figure out the 2nd dimension of ip tensor
  t=t.squeeze()
  return t

In [64]:
flatten(t1)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

**tensor concatination**

In [71]:
t1=torch.tensor(np.array([1,1,2]))
t2=torch.tensor(np.array([5,8,9]))
t3=torch.cat((t1,t2), dim=0)
t3

tensor([1, 1, 2, 5, 8, 9])

# **Video 11 Visualizing the FLATTEN operation**

**blog post** http://deeplizard.com/learn/video/mFAIBMbACMA

In [0]:
import torch

In [0]:
t1=torch.tensor([[1,1,1,1],
                [1,1,1,1],
                [1,1,1,1],
                [1,1,1,1]])


t2=torch.tensor([[2,2,2,2],
                [2,2,2,2],
                [2,2,2,2],
                [2,2,2,2]])

t3=torch.tensor([[3,3,3,3],
                [3,3,3,3],
                [3,3,3,3],
                [3,3,3,3]])


We are creating a batch of these 3 tensors, consider this tensors as images. We want to combine the tensors in such a way that the new tensor has 3 axes i.e. rank 3 tensor

In [5]:
t=torch.stack((t1,t2,t3))
t.shape

torch.Size([3, 4, 4])

In [6]:
t


tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])

[3, 4, 4] is the size of new tensor, 3 denotes the batch size i.e. there are 3 tensors in a batch and (4,4 ) is height and width of the tensors.
now we should add one more axis to this tensor to make it accepatable as cnn ip i.e the color channel axis. 

In [8]:
t=t.reshape(3,1,4,4)
t

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

adding one more axis doesn't change the dimension of the tensor as the multiplication of the given dimensions(3,1,4,4,) is still same as (3,4,4)

to observe the change in the dimension notice the number of square brackets in this and above op of t

![four axes of the new tensors](https://ibb.co/PFdKfQ8)


The first Image

In [9]:
t[0]

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])

The first color channel

In [10]:
t[0][0]

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

First row of pixel in the first color channel of the first image

In [11]:
t[0][0][0]

tensor([1, 1, 1, 1])

the first pixel value in the first color channel of the first image

In [12]:
t[0][0][0][0]

tensor(1)

The whole batch is a single tensor (collection of images )so we dont want to flatten the whole tensor, we just want to flattent the image part from this tensor

lets first see the various ways to flatten the whole tensor

In [13]:
t.reshape(-1)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [14]:
t.reshape(1,-1)[0]


tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [15]:
t.view(t.numel())

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [16]:
t.flatten()

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

this smashes all of the images from the batches into a single axis hence we are mixing the images this wont work 

we want to flatten the color channel axis with the height and width axis

In [17]:
t.flatten(start_dim=1).shape

torch.Size([3, 16])

In [18]:
t.flatten(start_dim=1)  #start_dim tells the flatten function where to start the flattening operation, 1 is our 2nd axis as dimensions start from 0

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

trying above operation with reshape function

In [22]:
t.reshape([3,16])

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

# Video 12 Element wise operation and broadcasting

blog post of the video http://deeplizard.com/learn/video/QscEWm0QTRY

In [0]:
import torch
import numpy as np

In [0]:
t1=torch.tensor([[1,5], [7,8]], dtype=torch.float32)
t2=torch.tensor([[9,2],[10,4]],dtype=torch.float32)

In [16]:
t1


tensor([[1., 5.],
        [7., 8.]])

In [17]:
t2

tensor([[ 9.,  2.],
        [10.,  4.]])

**Element wise operation
Two tensor must have same shape and same no of axis and each of axes should have same length.**

In [18]:
t1+t2

tensor([[10.,  7.],
        [17., 12.]])

In [19]:
t1-t2

tensor([[-8.,  3.],
        [-3.,  4.]])

In [20]:
t1*t2


tensor([[ 9., 10.],
        [70., 32.]])

In [21]:
t1/t2

tensor([[0.1111, 2.5000],
        [0.7000, 2.0000]])

Elementwise operation with scalers

In [22]:
t1-2 # or t1.sub(2)

tensor([[-1.,  3.],
        [ 5.,  6.]])

In [23]:
t2+2 #or t2.add(2) similarly mul() and div()

tensor([[11.,  4.],
        [12.,  6.]])

How scalers can operate on tensors in elementwise operations  when we need  tensors of same shape??
scalers are rank 0 tensors so they have no shape. But this is not what exactly happens.
What happens is **boradcasting**

Broadcasting is making the scalar of the same shape of tensor you want your scalar to operate on 

In [24]:
t1+2

tensor([[ 3.,  7.],
        [ 9., 10.]])

what happens in the background is

In [26]:
np.broadcast_to(2, t1.shape) #broadcast 2 to the shape of tensor t1

array([[2, 2],
       [2, 2]])

broadcasting a tensor can make elementwise operations between 2 tensors of different size possible. 

In [0]:
t1=torch.tensor([[2,4],[9,6]])

In [28]:
t1.shape

torch.Size([2, 2])

In [0]:
t2=torch.tensor([1,1])

In [30]:
t2.shape

torch.Size([2])

In [31]:
t1+t2

tensor([[ 3,  5],
        [10,  7]])

what happened in the background is

In [33]:
np.broadcast_to(t2, t1.shape) #and then t1+t2

array([[1, 1],
       [1, 1]])

Comparison operations
they also have broadcasting in the background

In [34]:
t1


tensor([[2, 4],
        [9, 6]])

In [35]:
t2

tensor([1, 1])

In [37]:
t1.gt(t2) #t2 is gettign groadcasted to the shape of t1 before comparison happens and then as t1>t2 in all the position a new tensor of same shape of t1 with all ones is returned

tensor([[1, 1],
        [1, 1]], dtype=torch.uint8)

In [39]:
t2.eq(t1) #here t1 got broadcasted to the shape of t2

tensor([[0, 0],
        [0, 0]], dtype=torch.uint8)

# Video 13 argmax and reduction tensor ops

Reduction operation reduces the number of elements present in a tensor
elementwise operations need two tensors to opearte element wise in between them.
Reuction operation operates on elements of same tensor to reduce the number of elements in the tensor

In [41]:
t1=torch.tensor([[3,3,4],[5,7,9],[-1,-5,3]])
t1

tensor([[ 3,  3,  4],
        [ 5,  7,  9],
        [-1, -5,  3]])

In [43]:
t1.sum() #sum of the all elements of the tensor(reduces the number of elemts from 9 to 1)

tensor(28)

In [46]:
t1.numel() #no of elemts in tensor, reduces the number of elemts from 9 to 1

9

In [0]:
t1.sum()numel()<t1.numel()