<a href="https://colab.research.google.com/github/mvish7/PyTorch/blob/master/building_nn_layers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##video18

In [0]:
import torch
import torchvision
#import torchvision.transform as transforms
import torch.nn as nn
import torch.functional as F

Creating a class with n/w structure , inheriting the nn.module class to use methods such as conv2d, linear for class creation.

hint about super function: the super function can be used to gain access to inherited methods – from a parent or sibling class – that has been overwritten in a class object.

In [0]:
class Network(nn.Module):
  def __init__(self):
    super(Network,self).__init__()
    self.conv1 = nn.Conv2d(in_channels=1, out_channels=6, kernel_size=5)
    self.conv2 = nn.Conv2d(in_channels=6, out_channels=12, kernel_size=5)
    
    self.fc1 = nn.Linear(in_features=12*4*4, out_features=120)
    self.fc2 = nn.Linear(in_features=120, out_features=60)
    self.out = nn.Linear(in_features=60, out_features=10)
    
  def fwd_pass(self,t):
    #implementing fwd pass
    return t
  
  def __repr__(self):
    return "liznet"
      

## video 19

In [0]:
network=Network()

In [0]:
print(network) #string representations of network class, which is inheriting the nn.Module class. So in all nn class in torch has a fun for string representation
#this is how default print fun would print

Network(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 12, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=192, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=60, bias=True)
  (out): Linear(in_features=60, out_features=10, bias=True)
)


overriding the print functionality inherited from the base(nn) class. sop that we can print what we want for our class. this can be done by "def__repr__()"" func.

In [0]:
print(network) #this is how custom (overridden) print fun would print

liznet


getting info about n/w layers by using  **"."'**  function

In [0]:
network.conv1 #this is nothing but string representation if a layer

Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))

In [0]:
network.fc1

Linear(in_features=192, out_features=120, bias=True)

now accessing the weights of the network (layerwise)

In [0]:
network.conv1.weight

Parameter containing:
tensor([[[[ 0.0247, -0.1047,  0.0211,  0.1186, -0.0448],
          [ 0.0138, -0.0093, -0.1188,  0.0391, -0.1347],
          [ 0.0566,  0.1313, -0.1986,  0.0986, -0.1233],
          [ 0.1525,  0.0465,  0.0133,  0.0536, -0.0031],
          [-0.0864,  0.0019,  0.1104,  0.0089, -0.1869]]],


        [[[-0.0633,  0.1059,  0.0411,  0.0690, -0.0698],
          [-0.1135,  0.1928, -0.0204,  0.0375, -0.1929],
          [-0.1801,  0.0349,  0.0122,  0.0779, -0.1760],
          [-0.0889,  0.0721, -0.0967, -0.0626,  0.1486],
          [ 0.0277,  0.1479,  0.0841, -0.1512,  0.1431]]],


        [[[ 0.1870, -0.1043, -0.1414, -0.0851,  0.0129],
          [ 0.0123, -0.1522,  0.0161, -0.0972,  0.1473],
          [-0.1875, -0.1816, -0.1025,  0.0965, -0.0093],
          [ 0.0801, -0.1427,  0.1103, -0.1236, -0.0462],
          [-0.0632, -0.1241,  0.1784,  0.0051, -0.1093]]],


        [[[ 0.1894,  0.1703, -0.0453, -0.1918, -0.1981],
          [ 0.0072, -0.0535, -0.1580, -0.1554, -0.1292

torch has a class called parameter which extends a class called tensor, so weight tensor in each layer is a instance of parameter class. 
nn module class is looking for any attributes which are instances of parameter class, if it finds the instance of the parameter class and nn class keeps track of it

In [0]:
network.conv1.weight.shape

torch.Size([6, 1, 5, 5])

In [0]:
network.conv2.weight.shape

torch.Size([12, 6, 5, 5])

In [0]:
network.conv1.weight[-1].shape

torch.Size([1, 5, 5])

accessing the weight of the linear layers

In [0]:
network.fc1

Linear(in_features=192, out_features=120, bias=True)

In [0]:
network.fc1.weight

Parameter containing:
tensor([[-0.0275, -0.0297,  0.0547,  ...,  0.0345,  0.0057, -0.0504],
        [ 0.0594,  0.0338, -0.0414,  ...,  0.0400,  0.0019, -0.0309],
        [ 0.0016,  0.0205,  0.0054,  ...,  0.0142,  0.0371,  0.0022],
        ...,
        [ 0.0540,  0.0016,  0.0366,  ..., -0.0579,  0.0235,  0.0392],
        [ 0.0447, -0.0204, -0.0264,  ...,  0.0133, -0.0216, -0.0174],
        [ 0.0068, -0.0538,  0.0092,  ..., -0.0140, -0.0103,  0.0700]],
       requires_grad=True)

In [0]:
network.fc1.weight.shape

torch.Size([120, 192])

## video 20

lets see how linear layers maps the ip_features to op_features

In [0]:
import torch
import torch.nn as nn
ip_features=torch.tensor([1,2,3,4], dtype=torch.float32)

In [0]:
weight_matrix=torch.tensor([[1,2,3,4],
                          [2,3,4,5],
                          [3,4,5,6]], dtype=torch.float32)

In [0]:
weight_matrix.matmul(ip_features)

tensor([30., 40., 50.])

creating the pytorch linear layer which does the same operation

In [0]:
fc=nn.Linear(in_features=4, out_features=3)

now let's call the layer that we have made. we can call any layer like this cause torch nn layers are callable python modules

In [0]:
fc(ip_features) #essentially we paseed a tensor as ip here. values of this operations differ from our above matmul why??
#because TORCH CREATES A WEIGHT MATRIX AND INITIALIZES IT WITH RANDOM VALUES

tensor([0.5680, 0.0325, 0.2372], grad_fn=<AddBackward0>)

Now setting weight matrix same as we had previously
**remember to wrap weight matrix in parameter class**

In [0]:
fc.weight=nn.Parameter(weight_matrix)

now calling fc layer again with in_features

In [0]:
fc(ip_features)

tensor([30.0059, 39.8449, 50.2667], grad_fn=<AddBackward0>)

now see output comes near to the original matmul but still somewhat not the same, why??
**because of bias**


##video21 Implementing forward method

In [0]:
import torch
import torchvision
import torchvision.transforms as transforms
import torch.nn as nn
import torch.nn.functional as F

In [0]:
class Network(nn.Module):
  def __init__(self):
    super(Network,self).__init__()
    self.conv1 = nn.Conv2d(in_channels=1, out_channels=6, kernel_size=5)
    self.conv2 = nn.Conv2d(in_channels=6, out_channels=12, kernel_size=5)
    
    self.fc1 = nn.Linear(in_features=12*4*4, out_features=120)
    self.fc2 = nn.Linear(in_features=120, out_features=60)
    self.out = nn.Linear(in_features=60, out_features=10)
    
  def fwd_pass(self,t):
    #implementing fwd pass
    
    # input layer
    t=t #returning the tensor as it as, no need of processing
    
    # hidden layer 1 
    t=self.conv1(t)
    t=F.relu(t)
    t=F.max_pool2d(t, kernel_size=2, stride=2)
    
    
    #hidden layer 2
    t=self.conv2(t)
    t=F.relu(t)
    t=F.max_pool2d(t, kernel_size=2, stride=2)
    
    #hidden layer 3
    t=t.reshape(-1,12*4*4)  #doing the flattening operation before passing the tensor from conv layer to the linear layer
    t=self.fc1(t)
    t=F.relu(t)
    
    #hidden layer 4
    t=self.fc2(t)
    t=F.relu(t)
    
    #output layer
    t=self.out(t)
    #t=F.softmax(t, dim=1)  no need to use softmax here, coz we are using cross entropy as our loss function and it has built in softmax.
    
    
    return t
  
  def __repr__(self):
    return "liznet"
      